urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name= 'myapp'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('', views.loginpage, name='loginpage'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('registerpatient/', views.registerpatient, name='registerpatient'),
    path('predictionform/', views.predictionform, name='predictionform'),
    path('results/', views.results, name='results'),
    path('patientreport/', views.patientreport, name='patientreport'),
    path('logout/', views.logout, name='logout'),
    path('test/', views.test, name='test'),
    path('index/', views.index, name='index'),

    
]
urlpatterns += staticfiles_urlpatterns()



templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cabin&family=EB+Garamond&display=swap" rel="stylesheet">
    <title>Stroke Away| About Us</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'images/newlogo.jpg' %}">

</head>
<body>
    <div class="navCont">
       <div class="brandName">
        {% load static %}
           <img src="{% static 'images/newlogo.jpg' %}" alt="logo">
           <div class="text">Stroke Away</div>
        </div>
        <div class="navList">
          <a href="{% url 'myapp:home' %}"> Home</a>
          <!-- <a href="login.html">Login</a>-->
          <a href="{% url 'myapp:about' %}">About Us</a>
          <a href="{% url 'myapp:loginpage' %}">Logout</a>
       </div>
    </div>
 
           
                <div class="about"> Stroke Away is an interface for  “Obesity Screening and Stroke Risk Prediction System”, a system that diagnoses obesity, predicts the risk of stroke in a person and displays the result. Based on our hardware system and inputs provided, patients will be able to find out whether they're obese or not and register for Stroke risk prediction if they wish. Patients are also able to retrieve their medical data with the assistance of our nurse. By the means of our efficient system, we aim to bring awareness about their health conditions to our patients. 
                    <br>
               </div>
               <footer class="foot"> For further information Contact Us  <br> tha075bei026@tcioe.edu.np <br> tha075bei027@tcioe.edu.np <br> tha075bei029@tcioe.edu.np</footer>
        
    
    
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cabin&family=EB+Garamond&display=swap" rel="stylesheet">
    <title>Stroke Away| Home</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'images/newlogo.jpg' %}">

</head>
<body>
    <div class="navCont">
       <div class="brandName">
        {% load static %}
           <img src="{% static 'images/newlogo.jpg' %}" alt="logo">
           <div class="text">Stroke Away</div>
        </div>
        <div class="navList">
          <a href="{% url 'myapp:home' %}"> Home</a>
          <!-- <a href="login.html">Login</a>-->
          <a href="{% url 'myapp:about' %}">About Us</a>
          <a href = "{% url 'myapp:loginpage'%}">Logout</a>
       </div>
    </div>
 
  
        <div class="imgCont">
            {% load static %}
            <img src="{% static 'images/bgimg2.jpg' %}" alt="background image">
           
                <div class="des">We are here to predict  <br>
                    the  Stroke Risk for you<br>
                <button> <a  style="text-decoration: none;color: aliceblue;" href="{% url 'myapp:predictionform' %}">Try Us</a> </button>
            </div>
            <div class="nurseCont1">
                <a href="{% url 'myapp:registerpatient' %}">Register New Patient</a> 
                <a href="{% url 'myapp:predictionform' %}">Stroke Risk Prediction</a> 
                <a href="{% url 'myapp:patientreport' %}">Generate Patient Report</a> 
               </div>
        </div>
        
    
    
</body>
</html>

templates/index.html
<html lang="en">
   <head> 
      <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
      <meta http-equiv="X-UA-Compatible" content="ie=edge"> 
      <script src="https://code.jquery.com/jquery-3.3.1.js"></script> 
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.js"></script> 
      <title>Stroke Away|Reports </title> 
      <h1 style = "text-align: center; color: red;"> Reports generated from the data collected</h1>
      {% load static %}
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <script>
        $(function () {
            var ctx = document.getElementById("chart1").getContext('2d');
            var data = {
                datasets: [{
                    label: "Average Glucose Level in Male and Female",
                    data: [{% for data in fdata %} {{data.avg_glucose_level}}, {% endfor %}],
                    backgroundColor: [
                        '#3c8dbc',
                        '#f56954',
                        '#f39c12',
                    ],
                }],
                labels: ['Male', 'Female']
            };
            var mybarChart = new Chart(ctx, {
                type: 'bar',
                data: data,
                options: {
                    responsive: false,
                    maintainAspectRatio: false,
                    legend: {
                        position: 'bottom',
                        labels: {
                            boxWidth: 12
                        }
                    }
                }
            });

            var ctx_2 = document.getElementById("chart2").getContext('2d');
            var data_2 = {
                datasets: [{
                    label: "Average glucose level in residence type",
                    data: [{% for data in fdata %} {{data.avg_glucose_level}}, {% endfor %}],
                    backgroundColor: [
                        '#3c8dbc',
                        '#f56954',
                        '#f39c12',
                    ],
                }],
                labels: ['Urban', 'Rural']
            };
            var mybarChart_2 = new Chart(ctx_2, {
                type: 'bar',
                data: data_2,
                options: {
                    responsive: false,
                    maintainAspectRatio: false,
                    legend: {
                        position: 'bottom',
                        labels: {
                            boxWidth: 12
                        }
                    }
                }
            });

            var ctx = document.getElementById("chart3").getContext('2d');
            var data = {
                datasets: [{
                    label: "Smoking Status according to age",
                    data: [{% for data in fdata %} {{data.age}}, {% endfor %}],
                    backgroundColor: [
                        '#3c8dbc',
                        '#f56954',
                        '#42B557',
                        '#f39c12',
                    ],
                }],
                labels: ['Smokes', 'Formerly Smoked', 'Never Smoked', 'Unknown'],
            };
            var mybarChart_3 = new Chart(ctx, {
                type: 'bar',
                data: data,
                options: {
                    responsive: false,
                    maintainAspectRatio: false,
                    legend: {
                        position: 'bottom',
                        labels: {
                            boxWidth: 12
                        }
                    }
                }
            });

            var ctx = document.getElementById("chart4").getContext('2d');
            var data = {
                datasets: [{
                    label: 'Average glucose level for different work type',
                    data: [{% for data in fdata %} {{data.avg_glucose_level}}, {% endfor %}],
                    backgroundColor: [
                        '#3c8dbc',
                        '#f56954',
                        '#f39c12',
                        '#42B557',
                         '#2F3244',
                    ],
                }],
                labels: ['Private', 'Government', 'Self Employed', 'Children', 'Never Worked '],
            };
            var mybarChart_4 = new Chart(ctx, {
                type: 'bar',
                data: data,
                options: {
                    responsive: false,
                    maintainAspectRatio: false,
                    legend: {
                        position: 'bottom',
                        labels: {
                            boxWidth: 12
                        }
                    }
                }
            });

            var ctx = document.getElementById("chart5").getContext('2d');
            var data = {
                datasets: [{
                    label: 'Obesity level for different range of body fat',
                    data: [{% for data in pdata %} {{data.bodyfat}}, {% endfor %}],
                    backgroundColor: [
                    '#f39c12',
                    ],
                }],
                labels: ['Severe Obesity','Obesity II','Obesity I','Underweight','Normal'],
                // data: [{% for data in pdata %} {{data.bodyfat}}, {% endfor %}],
            };
            var mybarChart_5 = new Chart(ctx, {
                type: 'line',
                data: data,
                options: {
                    responsive: false,
                    maintainAspectRatio: false,
                    legend: {
                        position: 'bottom',
                        labels: {
                            boxWidth: 12
                        }
                    }
                }
            });

            var ctx = document.getElementById("chart6").getContext('2d');
            var data = {
                datasets: [{
                    label: 'Stroke Status according to body fat',
                    data: [{% for data in pdata %} {{data.bodyfat}}, {% endfor %}],
                    backgroundColor: [
                    '#f56954',
                        '#42B557',
                        
                    ],
                }],
                labels: ['Stroke Risk', 'No Stroke Risk'],
            };
            var mybarChart_6 = new Chart(ctx, {
                type: 'bar',
                data: data,
                options: {
                    responsive: false,
                    maintainAspectRatio: false,
                    legend: {
                        position: 'bottom',
                        labels: {
                            boxWidth: 12
                        }
                    }
                }
            });
        });
    
      </script> 
   </head> 
   <body> 
       <div class="reports" style="display: flex;justify-content: space-evenly;flex-wrap: wrap;margin: auto;">
      <div style = "float:left; margin-top:30px; margin-left:50px;"> 
         <canvas id="chart1" width="330px" height="330px"></canvas> 
      </div> 
      <div style = "float:left; margin-top:30px; margin-left:50px;"> 
         <canvas id="chart2" width="330px" height="330px" ></canvas> 
      </div>  
      <div style = "float:left; margin-top:30px; margin-left:50px;"> 
        <canvas id="chart3" width="330px" height="330px" ></canvas> 
     </div>  
     <div style = "float:left; margin-top:50px; margin-left:50px;"> 
        <canvas id="chart4" width="330px" height="330px" ></canvas> 
     </div>  
     <div style = "float:left; margin-top:50px; margin-left:50px;"> 
        <canvas id="chart5" width="400px" height="330px"></canvas> 
     </div>  
     <div style = "float:left; margin-top:50px; margin-left:50px;">  
        <canvas id="chart6" width="330px" height="330px"></canvas> 
     </div> 
    </div> 
   </body>
</html>

templates/loginpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cabin&family=EB+Garamond&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <script src="https://use.fontawesome.com/b4ca34aaa2.js"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <title>Login | Stroke Away</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'images/newlogo.jpg' %}">
</head>
<body>

    <div class="adminCont">
        <div class="brandName"  style=" margin-right:auto;margin-left:auto;padding-left:30%;margin-top:30px;">
            {% load static %}
            <img src="{% static 'images/newlogo.jpg' %}" alt="logo">
            <div class="text" style="margin-left: 10px;">Stroke Away</div>
         </div>
        <div class="adminCont1">
            <style>
                h3{
                    color:red;
                }
            </style>
            {% for message in messages %}
            <h3>{{message}}</h3>
            {% endfor %}
            <form method = "POST" action = "{% url 'myapp:loginpage' %}">
                {% csrf_token %}
                <input type="name" name="username" required placeholder="Username"><br>
           <!-- <input type="text" name="email"  required placeholder="Email"><br> -->
           <input  type="password" name="password" required class="id_password"  placeholder="Password"><br>
           <!-- <i class="far fa-eye togglePassword" style="margin-left: -24px; cursor: pointer;"></i><br> -->
           <button>Login</button>
                 <div class="text">Don't have an account? 
                     <a href="{% url 'myapp:signup' %}">Sign Up</a> </div> 
            </form>
        </div>
    </div>
</body>

</html>

templates/patientreport.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cabin&family=EB+Garamond&display=swap" rel="stylesheet">
    <title>Stroke Away| Results</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'images/newlogo.jpg' %}">
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'images/newlogo.jpg' %}">
</head>
<body>
    <div class="navCont">
       <div class="brandName">
        {% load static %}
           <img src="{% static 'images/newlogo.jpg' %}" alt="logo">
           <div class="text">Stroke Away</div>
        </div>
        <div class="navList">
          <a href="{% url 'myapp:home' %}"> Home</a>
          <!-- <a href="login.html">Login</a>-->
          <a href="{% url 'myapp:about' %}">About Us</a>
          <a href="{% url 'myapp:loginpage' %}">Logout</a>
       </div>
    </div>
     
        <div class="adminCont">
         
            <div class="regPatCont" style="top:17%;padding: 15px 5px 15px 5px;">
                
                <form method = "POST" action = "{% url 'myapp:patientreport' %}">
                    {% csrf_token %}
                    <!-- <input type="name" name="name" required  placeholder="Full Name"><br> -->
                    <input list="patients" name="patname" placeholder="Patient Name">
                     <datalist id="patients">
                {% for patient in patients %}
                   <option value="{{patient.id}}">{{patient.name}}</option>

                {% endfor %}
            </datalist><br>
                    <input type="number" name="contact" maxlenghth="10" required  placeholder="Contact number"><br>
                    
                    <button>Search</button>
                </form>
                
            </div>
            
            <div style="margin-top: 50px;
            color: #993358;
            font-size: 27px;text-align: center;">{% for message in messages %}
                <p>{{message}}</p>
                {% endfor %}</div>
            
            
            <div class="regPatCont" style="left:40%;top:45%; font-size: 22px; width: auto; height: auto;" >
                <!-- {% for message in messages %}
                <p>{{message}}</p>
                {% endfor %} -->
             {{pats_pat}}<br>{{pats_pat1}}<br>{{sens_pat}}<br>{{sens_pat1}}<br>{{f_pat}}<br>{{pred_pat}}<br>{{pred_pat1}}<br>{{pred_pat2}}<br>
            </div>
        </div>
   
    
</body>
</html>

templates/prediction.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cabin&family=EB+Garamond&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Prediction Model | Stroke Away</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'images/newlogo.jpg' %}">
</head>

<body>
    <div class="navCont">
        <div class="brandName">
            {% load static %}
            <img src="{% static 'images/newlogo.jpg' %}" alt="logo">
            <div class="text">Stroke Away</div>
        </div>
        <div class="navList">
            <a href="{% url 'myapp:home' %}"> Home</a>
            <!-- <a href="login.html">Login</a>-->
            <a href="{% url 'myapp:about' %}">About Us</a>
            <a href="{% url 'myapp:loginpage' %}">Logout</a>
        </div>
    </div>
    <div class="adminCont" >
       
        <form method="POST" action="{% url 'myapp:predictionform' %}" class="regPatCont" style="padding:10px;top:4%">
            {% csrf_token %}
            <!-- <input type="name" name="name" required placeholder="Full Name"><br> -->
            <input list="patients" name="patname" placeholder="Patient Name">
            <datalist id="patients">
                {% for patient in patients %}
                   <option value="{{patient.name}}">{{patient.name}}</option>

                {% endfor %}
            </datalist><br>
            <input list="gender" name="gender" placeholder="Gender">
            <datalist id="gender">
                <option value="Male">
                <option value="Female">
               
                
            </datalist><br>
            <input type="number" name="age" required placeholder="Age"><br>
            <input list="hypertension" name="hypertension" placeholder="Do you suffer from hypertension?">
            <datalist id="hypertension">
                <option value="Yes">
                <option value="No">
            </datalist><br>
            <input list="heartdisease" name="heart_disease" placeholder="Do you have any heartdiseases?">
            <datalist id="heartdisease">
                <option value="Yes">
                <option value="No">
            </datalist><br>
            <input list="marriage" name="ever_married" placeholder="Ever married?">
            <datalist id="marriage">
                <option value="Yes">
                <option value="No">
            </datalist><br>
            <input list="worktype" name="work_type" placeholder="Work Type">
            <datalist id="worktype">
                <option value="Private">
                <option value="Government Job">
                <option value="Self-employed">
                <option value="children">
                <option value="Never_worked">    
            </datalist><br>
            <input list="residence" name="Residence_type" placeholder="Residence">
            <datalist id="residence">
                <option value="Rural">
                <option value="Urban">
            </datalist><br>
            <input  type="number"
            step="0.01"
             name="avg_glucose_level" placeholder="Average glucose level"><br>
            <input list="smoking_status" name="smoking_status" placeholder="Smoking Status">
            <datalist id="smoking_status">
                <option value="formerly smoked">
                <option value="never smoked">
                <option value="smokes">
                <option value="Unknown">    

            </datalist><br>
            <input type="number" name="heartrate" oninput="javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);" maxlength="3" placeholder="Heart Rate"><br>
            <button>Submit </button>
           
        </form>

    </div>
    </div>
</body>

</html>

templates/registerpatient.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cabin&family=EB+Garamond&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Register Patient | Stroke Away</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'images/newlogo.jpg' %}">
</head>
<body>
    <div class="navCont">
        <div class="brandName">
            {% load static %}
            <img src="{% static 'images/newlogo.jpg' %}" alt="logo">
            <div class="text">Stroke Away</div>
         </div>
         <div class="navList">
           <a href="{% url 'myapp:home' %}"> Home</a>
           <!-- <a href="login.html">Login</a>-->
           <a href="{% url 'myapp:about' %}">About Us</a>
           <a href="{% url 'myapp:loginpage' %}">Logout</a>
        </div>
     </div>
     <div class="adminCont">
         
        <div class="regPatCont" style="top:10%;padding-top: 15px;padding-bottom: 15px;">
            {% for message in messages %}
                <h3 style="color: rgb(247, 18, 18);">{{message}}</h3>
                {% endfor %}
            <form method = "POST" action = "{% url 'myapp:registerpatient' %}">
                {% csrf_token %}
           <input type="name" name="name" required  placeholder="Full Name"><br>
           <!-- <input type="date" name="dob" required  placeholder="Date of Birth"><br> -->
           <input type="number" name="age" required  placeholder="Age"><br>
           <input type="name" name="address" required  placeholder="Address"><br>
           
           <input type="number" name="contact" oninput="javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);" maxlength="10" required  placeholder="Contact number"><br>
           <input type="email" name="email" required  placeholder="Email"><br>
           <!-- <input type="name" name="examined_by" required  placeholder="Examined By"><br> -->
           <button>Register</button>
        </form>
            
        </div>
    </div>
  
</body>
</html>

templates/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cabin&family=EB+Garamond&display=swap" rel="stylesheet">
    <title>Stroke Away| Results</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'images/newlogo.jpg' %}">
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'images/newlogo.jpg' %}">
</head>
<body>
    <div class="navCont">
       <div class="brandName">
        {% load static %}
           <img src="{% static 'images/newlogo.jpg' %}" alt="logo">
           <div class="text">Stroke Away</div>
        </div>
        <div class="navList">
          <a href="{% url 'myapp:home' %}"> Home</a>
          <!-- <a href="login.html">Login</a>-->
          <a href="{% url 'myapp:about' %}">About Us</a>
          <a href="{% url 'myapp:loginpage' %}">Logout</a>
       </div>
    </div>
     
     <div style="text-align: center;font-size: 30px;font-family:'EB Garamon', serif;padding: 30px ; border: 3px solid rgb(214 171 171);margin: 6% 30%;">   
        Stroke Status: {{answer}}<br>
       Body Fat Percentage: {{bodyfat}}%<br>
       Weight: {{weight}} kg<br>
       Height: {{height}} m<br>
       BMI: {{bmi}}<br>
       Obesity Level: {{obesity}}<br>
       
    </div>
    
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cabin&family=EB+Garamond&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://use.fontawesome.com/b4ca34aaa2.js"></script>
    <title>Sign Up | Stroke Away</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'images/newlogo.jpg' %}">
</head>
<body>


    <div class="adminCont">
        <div class="brandName"  style=" margin-right:auto;margin-left:auto;padding-left:30%;margin-top:20px;">
            {% load static %}
            <img src="{% static 'images/newlogo.jpg' %}" alt="logo">
            <div class="text" style="margin-left: 10px;">Stroke Away</div>
         </div>
        <div class="signCont1">
            <style>
                h3{
                    color:red;
                }
            </style>
            {% for message in messages %}
            <h3>{{message}}</h3>
            {% endfor %}
            <form method = "POST" action = "{% url 'myapp:signup' %}">
            {% csrf_token %}
            <input type="name" name="username" id="" required="" placeholder="Username"><br>
            <input type="name" name="first_name" id="" required="" placeholder="First Name"><br>
            <input type="name" name="last_name" id="" required="" placeholder="Last Name"><br>
           <input type="email" name="email" id="" required="" placeholder="Email"><br>
           <input type="password" name="password" id="" required="" class="id_password"  placeholder="Password">
           <!-- <i class="far fa-eye togglePassword" style="margin-left: -24px; cursor: pointer;"></i><br> -->
           <input type="password" name="confirmpassword" id="" required="" class="id_password"  placeholder="Confirm Password"><br>
           
          <!-- <i class="far fa-eye togglePassword" style="margin-left: -24px; cursor: pointer;"></i>-->
          <!-- <input type = "submit"/> -->
           <button>  Sign Up </button>
                 <div class="text">Already have an account?
                     <a href="{% url 'myapp:loginpage' %}">Login</a> </div> 
            </form>
            
        </div>
    </div>
    
</body>
<script src="icon.js"></script>
</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <!-- <form method = "POST" action = "{% url 'myapp:test' %}">
            {% csrf_token %}
            <input type="name" name="name" required  placeholder="Full Name"><br>
            
             <input type="number" name="contact" maxlenghth="10" required  placeholder="Contact number"><br> -->
            
            <!-- <button>Search</button>
        </form> --> 
        <!-- H: {{ht}} m<br>
        W: {{wt}} m<br> -->
       <!-- m: {{m1}} -->
        <!-- j:{{j}} -->
    </div>
</body>
</html>